app_web/blueprints/expenses/views.py
from flask import Blueprint, render_template,request,url_for,redirect,flash,jsonify
from models.user import User
from models.expense import Expense
from models.category import Category
from flask_login import current_user, login_required
from peewee import fn
from datetime import date
import os
import pdfkit
import datetime

expenses_blueprint = Blueprint('expenses',
                            __name__,
                            template_folder='templates')

@expenses_blueprint.before_request
@login_required
def before_request():
  pass

@expenses_blueprint.route('/new', methods=['GET'])
def new():
  categories = Category.select().where(Category.user==current_user.id)
  return render_template('expenses/new.html',categories=categories)


@expenses_blueprint.route('/<user_id>', methods=['POST'])
def create(user_id):
  user = User.get_by_id(user_id)
  category = Category.get_by_id(request.form.get('category'))
  expense = Expense(cat=category,category=category.name,amount=request.form.get('amount'),source=request.form.get('source'),description=request.form.get('desc'))
  if expense.save():
    flash("Successfully create expense record.","primary")
    return redirect(url_for('expenses.show',category="all"))
  else:
    flash("Something happened, try again later.","danger")
    categories = Category.select().where(Category.user==current_user.id)
    return render_template('expenses/new.html',categories=categories)

@expenses_blueprint.route('/<category>')
def show(category):
  current = datetime.datetime.now()
  categories = Category.select().where(Category.user==current_user.id).order_by(Category.created_at.desc())
  if current_user.is_authenticated:
    if category == 'all':
      expenses = Expense.select().join(Category).where(
        Category.user == current_user.id,
        Expense.month == date.today().strftime("%b"),
        Expense.created_at.year == current.year
        ).order_by(Expense.created_at.asc()
      )
    else:
      selected = Category.get(Category.name==category)
      expenses = Expense.select().where(Expense.cat==selected.id,Expense.month==date.today().strftime("%b"),Expense.created_at.year==current.year).order_by(Expense.created_at.asc())
    total = 0
    for exp in expenses:
      total += exp.amount
    return render_template('expenses/show.html', expenses=expenses, total=total, cat=category, categories=categories)
  return render_template('sessions/new.html')  

@expenses_blueprint.route('/edit/<id>',methods=["GET"])
def edit(id):
  categories = Category.select().where(Category.user==current_user.id)
  expense = Expense.get_by_id(id)
  return render_template('expenses/edit.html',expense=expense, categories=categories)  
    
@expenses_blueprint.route('/<id>/update',methods=["POST"])
def update(id):
  if current_user.is_authenticated:
    expense = Expense.get_by_id(id)
    category = Category.get(Category.name==request.form.get('category'))
    expense.cat = category.id
    expense.category = category.name
    expense.source = request.form.get('source')
    expense.desc = request.form.get('desc')
    expense.amount = request.form.get('amount')
    if expense.save():
      flash("Successfully update expense record.","primary")
      return redirect(url_for('expenses.edit',id=expense.id))
    else:
      flash("Something happened, try again later.","danger")
      return render_template('expenses/edit.html',expense=expense) 
  return render_template('sessions/new.html')  

@expenses_blueprint.route('/delete/<id>',methods=["GET"])
def delete(id):
  expense = Expense.get_or_none(id=id)
  if not expense:
    flash("No expense record found.", "danger")
  else :
    expense.delete_instance()
    flash("Expense record successfully deleted.", "primary")

  return redirect(url_for('expenses.show',category="all"))


@expenses_blueprint.route('/summary',methods=["GET"])
def summary_list():
  months = [] 
  for cat in current_user.categories:
    for expense in cat.expenses:
      if not f"{expense.month}-{expense.created_at.year}" in months:
        months.append(f"{expense.month}-{expense.created_at.year}")
  return render_template('expenses/list.html',months=months)

@expenses_blueprint.route('/<month_year>/summary',methods=["GET"])
def summary(month_year):
  month_exp = []
  for cat in current_user.categories:
    cat_exp = []
    for expense in cat.expenses:
      mth_yr = month_year.split('-')
      month = mth_yr[0]
      year = mth_yr[1]
      if expense.month == month.title() and expense.created_at.year == int(year):
        cat_exp.append(expense)
    month_exp.append({
      "name":cat.name,
      "expenses":cat_exp
    })
  total = Expense.select().where(Expense.month==month.title(), Expense.created_at.year==year)
  return render_template('expenses/summary.html', month_exp=month_exp, month=month, total=total, month_year=month_year)

 

app_web/blueprints/reminders/views.py
from flask import Blueprint, render_template,request,url_for,redirect,flash,jsonify
from models.user import User
from models.reminder import Reminder
from flask_login import current_user, login_required
from peewee import fn
from datetime import date

reminders_blueprint = Blueprint('reminders',
                            __name__,
                            template_folder='templates')

@reminders_blueprint.before_request
@login_required
def before_request():
  pass

@reminders_blueprint.route('/new', methods=['GET'])
def new():
  return render_template('reminders/new.html')


@reminders_blueprint.route('/<user_id>', methods=['POST'])
def create(user_id):
  user = User.get_by_id(user_id)
  if request.form.get('dateRequired') == "on":
    reminder = Reminder(user=user.id,group=request.form.get('group'),description=request.form.get('desc'),dateline=request.form.get('dateline'))
  else:
    reminder = Reminder(user=user.id,group=request.form.get('group'),description=request.form.get('desc'))

  if reminder.save():
    flash("Successfully add reminder.","primary")
    return redirect(url_for('reminders.show',group="all"))
  else:
    flash("Something happened, try again later.","danger")
    return render_template('reminders/new.html')

@reminders_blueprint.route('/<group>', methods=['GET'])
def show(group):
  if current_user.is_authenticated:
    if group == 'all':
      reminders = Reminder.select().where(Reminder.user==current_user.id).order_by(Reminder.created_at.asc())
    else:
      reminders = Reminder.select().where(Reminder.group==group.title(),Reminder.user==current_user.id).order_by(Reminder.created_at.asc())
    return render_template('reminders/show.html',reminders=reminders)
  return render_template('reminders/new.html')

@reminders_blueprint.route('/<id>/edit', methods=['POST'])
def edit(id):
  reminder = Reminder.get_by_id(id)
  reminder.status = not reminder.status
  if reminder.save():
    flash("Successfully update.","primary")
    return redirect(url_for('reminders.show',group=reminder.group.lower()))
  else:
    flash("Something happened, try again later.","danger")
    return render_template('reminders/show.html',reminders=reminders)

app_web/blueprints/statements/views.py
from flask import Blueprint, render_template,request,url_for,redirect,flash,jsonify
from models.user import User
from models.statement import Statement
from flask_login import current_user, login_required
import json

statements_blueprint = Blueprint('statements',
                            __name__,
                            template_folder='templates')

@statements_blueprint.route('/', methods=['GET'])
@login_required
def index():
  statements = Statement.select().where(Statement.user==current_user.id).order_by(Statement.created_at.desc())
  return render_template("statements/new.html",statements=statements)

app_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, jsonify
from models.user import User
from models.expense import Expense
from models.category import Category
from flask_login import login_user, current_user, login_required
import datetime
from peewee import fn
from decimal import *

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
  return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():
  user_password = request.form['password']
  user = User(username=request.form['username'].lower(),email=request.form['email'].lower(),password=user_password)
  if user.save():
    login_user(user)
    Category.create(name="General Expenses", user=user.id)
    flash("Welcome! Start tracking your money by recording your expenses according to Category.","link")
    return redirect(url_for('users.show', username=user.username))
  else:
    for error in user.errors:
      flash(error,"danger")
    return render_template('users/new.html')

@users_blueprint.route('/<username>', methods=["GET"])
@login_required
def show(username):
  user = User.get_or_none(User.username == username)
  if not user:
    flash("User not found.", "danger")
    return redirect(url_for('user.show', username = current_user.username))
  else:
    if current_user.id == user.id:
      return render_template('users/show.html',username=user.username)
    else:
      flash("Unauthorized to visit this user's profile.", "danger")
      return redirect(url_for('user.show', username = current_user.username))
    

@users_blueprint.route('/<id>', methods=['POST'])
@login_required
def update(id):
  user = User.get_or_none(id=id)
  user.password = request.form['password']
  user.email = request.form['email']
  user.username = request.form['username']
  if user.save():
    flash("Profile updated.","link")
    return redirect(url_for('users.show', username=user.username))
  else:
    for error in user.errors:
      flash(error,"danger")
    return redirect(url_for('users.show', username=user.username))

@users_blueprint.route('/dashboard', methods=["GET"])
@login_required
def dashboard():

  def _get_last_twelve(current):
    last_twelve = [] # last 12months
    # check current month and year => 1, 2021
    month = current.month
    year = current.year
    for i in range(12):  # loop for 12 times
      # if month - 1 not equal to zero, then year == current.year, else year == current.year - 1 and month == 12
      if not month == 0:
        last_twelve.append((year, month))
      else:
        month = 12
        year = year - 1
        last_twelve.append((year, month))
      month = month - 1
    last_twelve.reverse()
    return last_twelve

  def _get_category_monthly_total(category,twelve):
    expenses_list = []
    for pairs in twelve:
      ttl = Expense.select(fn.SUM(Expense.amount).alias('total')).where(Expense.cat == category, Expense.month==months[pairs[1]],Expense.created_at.year==pairs[0])
      expenses_list.append(0 if ttl[0].total == None else str(ttl[0].total))
    return expenses_list

  months = { 1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec' }
  categories = Category.select().where(Category.user==current_user.id)
  current = datetime.datetime.now()
  twelve = _get_last_twelve(current)

  data = {}
  '''format of data
  data = { 
    "General" : 100 ,
    "Food" : 150 ,
  }
  '''
  result = {}
  '''format of result
  result = {
    "Total": [],
    "General": [],
  }
  '''
  month_labels = []
  aggregate = [] # to collect aggregate expenses for each month
  category_labels = []
  category_ids = []

  for cat in categories:
    category_labels.append(cat.name)
    category_ids.append(cat.id)
    result[cat.name] = _get_category_monthly_total(cat, twelve)

  for pairs in twelve:
    ttl = Expense.select(fn.SUM(Expense.amount).alias('total')).where(Expense.cat.in_(category_ids), Expense.month==months[pairs[1]],Expense.created_at.year==pairs[0])
    month_labels.append(f"{months[pairs[1]]}, {pairs[0]}")
    aggregate.append(0 if ttl[0].total == None else str(ttl[0].total))
  result["Total"] = aggregate
  print(result['Total'][11])
  return render_template(
    'users/dashboard.html', 
    labels = category_labels, 
    month_year = f'{datetime.date.today().strftime("%b")} {current.year}',
    month_labels = month_labels,
    main_values = result,
  )

app_web/templates/_footer.html
<footer>
  © 2021 
  <span class="mx-2">
    | 
  </span>
  <a href="https://github.com/leongjinqwen" target="_blank">
    Jinq Wen Leong
  </a>
</footer>

app_web/templates/_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

    {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
      <link rel="stylesheet" media="print" href="/static/css/print.css">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    {% endassets %}

    {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
      <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    {% endassets %}
    
    {% block header %}
    {% endblock %}

    <title>
      {% block title %}
      {% endblock %}| Personal
    </title>

  </head>
  <body>
    {% include "navbar.html" %}

    <!-- flash message -->
    <div>
      {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
          {% for category,message in messages %}
            <div class="notification is-{{category}}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>

    <div class="container is-fluid p-0">
      {% block content %}{% endblock %}
    </div>
    
    {% include "_footer.html" %}
  </body>
</html>

app_web/templates/home.html
{% extends "_layout.html" %}
{% block title %}
  Home
{% endblock %}
{% block content %}
<h1>HomePage</h1>

{% endblock %}

app_web/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand icon-text align-items-center" href="/">
    <img src="{{ url_for('static', filename='images/favicon.ico') }}" width="35" alt="logo">
    <span class="text-dark mx-2">|</span>
    <span class="text-dark">Home</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
    <ul class="navbar-nav">
      <div></div>
    </ul>
    <ul class="navbar-nav d-flex icon-text align-items-center ">
      <span class="icon has-text-dark">
        <i class="fas fa-calendar"></i>
      </span>
      <span class="text-dark">Today is {{ today }} !</span>
    </ul>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="reminderDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Reminder
        </a>
        <div class="dropdown-menu" aria-labelledby="reminderDropdown">
          <a class="nav-link dropdown-item" href="{{url_for('reminders.new')}}">Add</a>
          <a class="nav-link dropdown-item" href="{{url_for('reminders.show',group='all')}}">List</a>
        </div>
      </li> -->
      <li class="nav-item dropdown">
        <a class="nav-link d-flex icon-text align-items-center dropdown-toggle" href="#" id="expensesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="icon has-text-dark">
            <i class="fas fa-wallet"></i>
          </span>
          <span class="text-dark">Expenses</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="expensesDropdown">
          <a class="nav-link d-flex icon-text align-items-center dropdown-item" href="{{url_for('expenses.new')}}">
            <span class="icon has-text-dark">
              <i class="fas fa-plus-square"></i>
            </span>
            <span class="text-dark">Add</span>
          </a>
          <a class="nav-link d-flex icon-text align-items-center dropdown-item" href="{{url_for('expenses.show',category='all')}}">
            <span class="icon has-text-dark">
              <i class="fas fa-list-alt"></i>
            </span>
            <span class="text-dark">Expenses Listing</span>
          </a>
          <a class="nav-link d-flex icon-text align-items-center dropdown-item" href="{{url_for('expenses.summary_list')}}">
            <span class="icon has-text-dark">
              <i class="fas fa-folder"></i>
            </span>
            <span class="text-dark">Monthly Summary</span>
          </a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link d-flex icon-text align-items-center dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="icon has-text-dark">
            <i class="fas fa-user-circle"></i>
          </span>
          <span class="text-dark">Profile</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="profileDropdown">
          <a class="nav-link d-flex icon-text align-items-center dropdown-item" href="{{url_for('users.show', username=current_user.username)}}">
            <span class="icon has-text-dark">
              <i class="fas fa-cog"></i>
            </span>
            <span class="text-dark">Setting</span>
          </a>
          <a class="nav-link d-flex icon-text align-items-center dropdown-item" href="{{url_for('statements.index')}}">
            <span class="icon has-text-dark">
              <i class="fas fa-file-download"></i>
            </span>
            <span class="text-dark">Monthly Statement</span>
          </a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex icon-text align-items-center " href="{{url_for('sessions.logout')}}">
          <span class="icon has-text-dark">
            <i class="fas fa-sign-out-alt"></i>
          </span>
          <span class="text-dark">Logout</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link d-flex icon-text align-items-center " href="{{url_for('sessions.new')}}">
          <span class="icon has-text-dark">
            <i class="fas fa-sign-in-alt"></i>
          </span>
          <span class="text-dark">Sign In</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex icon-text align-items-center " href="{{url_for('users.new')}}">
          <span class="icon has-text-dark">
            <i class="fas fa-user-plus"></i>
          </span>
          <span class="text-dark">Sign Up</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>