app_web/blueprints/reminder/views.py
from flask import Blueprint, render_template,request,url_for,redirect,flash,jsonify
from models.user import User
from models.reminder import Reminder
from flask_login import current_user
from peewee import fn
from datetime import date

reminder_blueprint = Blueprint('reminder',
                            __name__,
                            template_folder='templates')


@reminder_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('reminder/new.html')


@reminder_blueprint.route('/<user_id>', methods=['POST'])
def create(user_id):
    user = User.get_by_id(user_id)
    if request.form.get('dateRequired') == "on":
        reminder = Reminder(user=user.id,group=request.form.get('group'),description=request.form.get('desc'),dateline=request.form.get('dateline'))
    else:
        reminder = Reminder(user=user.id,group=request.form.get('group'),description=request.form.get('desc'))

    if reminder.save():
        flash("Successfully add reminder.","primary")
        return redirect(url_for('users.show',username=user.username))
    else:
        flash("Something happened, try again later.","danger")
        return render_template('reminder/new.html')

@reminder_blueprint.route('/<group>', methods=['GET'])
def show(group):
    if current_user.is_authenticated:
        if group == 'all':
            reminders = Reminder.select().where(Reminder.user==current_user.id).order_by(Reminder.created_at.asc())
        else:
            reminders = Reminder.select().where(Reminder.group==group.title(),Reminder.user==current_user.id).order_by(Reminder.created_at.asc())
        return render_template('reminder/show.html',reminders=reminders)
    return render_template('reminder/new.html')

@reminder_blueprint.route('/<id>/edit', methods=['POST'])
def edit(id):
    reminder = Reminder.get_by_id(id)
    reminder.status = not reminder.status
    if reminder.save():
        flash("Successfully update.","primary")
        return redirect(url_for('reminder.show',group=reminder.group.lower()))
    else:
        flash("Something happened, try again later.","danger")
        return render_template('reminder/show.html',reminders=reminders)

app_web/blueprints/reminder/templates/reminder/new.html
{% extends "_layout.html" %}
{% block title %}
  New Reminder
{% endblock %}
{% block content %}
<h1>Add reminder</h1>
<form action="{{url_for('reminder.create',user_id=current_user.id)}}" method="POST">      
    <div class="form-group">
        <label for="group">Group:</label>
        <select name='group' class="custom-select" id="select1">
            <option selected>Choose...</option>
            <option value="Personal">Personal</option>
            <option value="Work">Work</option>
        </select>
    </div>
    <div class="form-group">
        <label for="desc">Description:</label>
        <input type='text' required name='desc' class="form-control" / >
    </div>
    <div class="form-group">
        <input type="checkbox" name="dateRequired" id="checkbox">
        <label for="date">Dateline:</label>
        <input type="date" id="date" class="form-control" name="dateline" disabled / >
    </div>
    <button type="submit" class="btn btn-outline-primary">Add</button>
</form>
<script>
    $("#checkbox").change(function(){
        $("#date").attr('disabled',!$("#date").attr('disabled'))
    })
</script>
{% endblock %}

app_web/blueprints/reminder/templates/reminder/show.html
{% extends "_layout.html" %}
{% block title %}
  Expenses
{% endblock %}
{% block content %}
<!-- <h1>{{current_user.id}}</h1> -->
<h3>Reminder</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Date</th>
      <th scope="col">Group</th>
      <th scope="col">Description</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    {% for reminder in reminders %}
      <tr>
        <td>{{reminder.id}}</td>
        <td>{{reminder.created_at.date().strftime("%b %d, %Y")}}</td>
        <td>{{reminder.group}}</td>
        <td>{{reminder.description}}</td>
        <form action="{{url_for('reminder.edit',id=reminder.id)}}" method="POST" id="form{{reminder.id}}">
          <td>
            <input type="checkbox" name="markDone" class="done mr-2" id={{reminder.id}}>
            {% if reminder.status %}
            Done
            {% else %}
            Pending
            {% endif %}
          </td>
        </form>
      </tr>
    {% endfor %}
  </tbody>
</table>
<script>
  $(".done").change(function(e){
    $(`#form${e.target.id}`).submit()
  })
</script>
{% endblock %}