app_web/blueprints/expenses/views.py
from flask import Blueprint, render_template,request,url_for,redirect,flash,jsonify
from models.user import User
from models.expense import Expense
from models.category import Category
from flask_login import current_user, login_required
from peewee import fn
from datetime import date
import os
import pdfkit
import datetime

expenses_blueprint = Blueprint('expenses',
                            __name__,
                            template_folder='templates')

@expenses_blueprint.before_request
@login_required
def before_request():
  pass

@expenses_blueprint.route('/new', methods=['GET'])
def new():
  categories = Category.select().where(Category.user==current_user.id)
  return render_template('expenses/new.html',categories=categories)


@expenses_blueprint.route('/<user_id>', methods=['POST'])
def create(user_id):
  user = User.get_by_id(user_id)
  category = Category.get_by_id(request.form.get('category'))
  expense = Expense(cat=category,category=category.name,amount=request.form.get('amount'),source=request.form.get('source'),description=request.form.get('desc'))
  if expense.save():
    flash("Successfully create expense record.","primary")
    return redirect(url_for('expenses.show',category="all"))
  else:
    flash("Something happened, try again later.","danger")
    categories = Category.select().where(Category.user==current_user.id)
    return render_template('expenses/new.html',categories=categories)

@expenses_blueprint.route('/<category>')
def show(category):
  current = datetime.datetime.now()
  categories = Category.select().where(Category.user==current_user.id).order_by(Category.created_at.desc())
  if current_user.is_authenticated:
    if category == 'all':
      expenses = Expense.select().join(Category).where(
        Category.user == current_user.id,
        Expense.month == date.today().strftime("%b"),
        Expense.created_at.year == current.year
        ).order_by(Expense.created_at.asc()
      )
    else:
      selected = Category.get(Category.name==category)
      expenses = Expense.select().where(Expense.cat==selected.id,Expense.month==date.today().strftime("%b"),Expense.created_at.year==current.year).order_by(Expense.created_at.asc())
    total = 0
    for exp in expenses:
      total += exp.amount
    return render_template('expenses/show.html', expenses=expenses, total=total, cat=category, categories=categories)
  return render_template('sessions/new.html')  

@expenses_blueprint.route('/edit/<id>',methods=["GET"])
def edit(id):
  categories = Category.select().where(Category.user==current_user.id)
  expense = Expense.get_by_id(id)
  return render_template('expenses/edit.html',expense=expense, categories=categories)  
    
@expenses_blueprint.route('/<id>/update',methods=["POST"])
def update(id):
  if current_user.is_authenticated:
    expense = Expense.get_by_id(id)
    category = Category.get(Category.name==request.form.get('category'))
    expense.cat = category.id
    expense.category = category.name
    expense.source = request.form.get('source')
    expense.desc = request.form.get('desc')
    expense.amount = request.form.get('amount')
    if expense.save():
      flash("Successfully update expense record.","primary")
      return redirect(url_for('expenses.edit',id=expense.id))
    else:
      flash("Something happened, try again later.","danger")
      return render_template('expenses/edit.html',expense=expense) 
  return render_template('sessions/new.html')  

@expenses_blueprint.route('/delete/<id>',methods=["GET"])
def delete(id):
  expense = Expense.get_or_none(id=id)
  if not expense:
    flash("No expense record found.", "danger")
  else :
    expense.delete_instance()
    flash("Expense record successfully deleted.", "primary")

  return redirect(url_for('expenses.show',category="all"))


@expenses_blueprint.route('/summary',methods=["GET"])
def summary_list():
  months = [] 
  for cat in current_user.categories:
    for expense in cat.expenses:
      if not f"{expense.month}-{expense.created_at.year}" in months:
        months.append(f"{expense.month}-{expense.created_at.year}")
  return render_template('expenses/list.html',months=months)

@expenses_blueprint.route('/<month_year>/summary',methods=["GET"])
def summary(month_year):
  month_exp = []
  for cat in current_user.categories:
    cat_exp = []
    for expense in cat.expenses:
      mth_yr = month_year.split('-')
      month = mth_yr[0]
      year = mth_yr[1]
      if expense.month == month.title() and expense.created_at.year == int(year):
        cat_exp.append(expense)
    month_exp.append({
      "name":cat.name,
      "expenses":cat_exp
    })
  total = Expense.select().where(Expense.month==month.title(), Expense.created_at.year==year)
  return render_template('expenses/summary.html', month_exp=month_exp, month=month, total=total, month_year=month_year)

 

app_web/blueprints/expenses/templates/expenses/edit.html
{% extends "_layout.html" %}
{% block title %}
  Update Expense
{% endblock %}
{% block content %}
<div id="edit-expense">
  <section class="hero is-info">
    <div class="hero-body">
      <div class="container">
        <h1 class="subtitle">Update Expense</h1>
      </div>
    </div>
  </section>
  <div class="form-item card">
    <form action="{{url_for('expenses.update',id=expense.id)}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <div class="field">
        <label class="label" for="category">Category</label>
        <select name='category' class="custom-select">
          {% for cat in categories %}
            <option value="{{cat.id}}" {{'selected' if expense.cat == cat }}>{{cat.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="field">
        <label class="label" for="source">Source</label>
        <select name='source' class="custom-select">
          <option {{'selected' if expense.source == "Cash" }} value="Cash">Cash</option>
          <option {{'selected' if expense.source == "Online" }} value="Online">Online Banking</option>
          <option {{'selected' if expense.source == "Bigpay" }} value="Bigpay">Bigpay</option>
          <option {{'selected' if expense.source == "Boost" }} value="Boost">Boost</option>
          <option {{'selected' if expense.source == "Grabpay" }} value="Grabpay">Grabpay</option>
          <option {{'selected' if expense.source == "TnG" }} value="TnG">Touch n Go</option>
        </select>
      </div>
      <div class="field">
        <label class="label" for="desc">Description</label>
        <input type='text' required name='desc' class="input" value={{expense.description}} />
      </div>
      <div class="field">
        <label class="label" for="amount">Amount</label>
        <div class="input-group mb-3">
          <div class="input-group-append">
            <span class="input-group-text">$</span>
            <input id="amount" name="amount" type="number" min="1" value={{expense.amount}} required placeholder="Amount" step="0.01">
          </div>
        </div>
      </div>
      <button type="submit" class="button is-fullwidth is-info">Update</button>
    </form>
  </div>
</div>
{% endblock %}

app_web/blueprints/expenses/templates/expenses/list.html
{% extends "_layout.html" %}
{% block title %}
  Summary List
{% endblock %}

{% block content %}
<div class="container my-5">
  <nav class="panel is-link">
    <p class="panel-heading">
      Monthly Expenses Summary
    </p>
    {% for month in months %}
      <a class="panel-block" href="{{url_for('expenses.summary',month_year=month)}}">
        <span class="panel-icon has-text-link">
          <i class="fas fa-clipboard-list"></i>
        </span>
        <span class="text-dark">{{month}}</span>
      </a>
    {% endfor %}
  </nav>
</div>

{% endblock %}

app_web/blueprints/expenses/templates/expenses/new.html
{% extends "_layout.html" %}
{% block title %}
  Record Expense
{% endblock %}
{% block content %}
<div id="create-expense">
  <section class="hero is-link">
    <div class="hero-body">
      <div class="container">
        <h1 class="subtitle">Record New Expense</h1>
      </div>
    </div>
  </section>
  <div class="form-item card">
    <form action="{{url_for('expenses.create',user_id=current_user.id)}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <div class="field">
        <label class="label" for="category">Category</label>
        <select name='category' class="custom-select">
          <option selected>Choose...</option>
          {% for cat in categories %}
            <option value="{{cat.id}}">{{cat.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="field">
        <label class="label" for="source">Source</label>
        <select name='source' class="custom-select">
          <option selected>Choose...</option>
          <option value="Cash">Cash</option>
          <option value="Online">Online Banking</option>
          <option value="Bigpay">Bigpay</option>
          <option value="Boost">Boost</option>
          <option value="Grabpay">Grabpay</option>
          <option value="TnG">Touch n Go</option>
        </select>
      </div>
      <div class="field">
        <label class="label" for="desc">Description</label>
        <input type='text' required name='desc' class="input" />
      </div>
      <div class="field">
        <label class="label" for="amount">Amount</label>
        <div class="input-group mb-3">
          <div class="input-group-append">
            <span class="input-group-text">$</span>
            <input id="amount" name="amount" type="number" min="1" value='0'required placeholder="Amount" step="0.01">
          </div>
        </div>
      </div>
      <button type="submit" class="button is-fullwidth is-link">Record</button>
    </form>
  </div>
</div>
{% endblock %}

app_web/blueprints/expenses/templates/expenses/show.html
{% extends "_layout.html" %}
{% block title %}
  Expenses
{% endblock %}

{% block header %}
  <style>
    td,th {
      border-left:1px solid #dee2e6;
      border-right:1px solid #dee2e6;
    }
    table {
      border-top: 1px solid #dee2e6;
      border-bottom: 1px solid #dee2e6;
    }
    .is-active {
      color: black !important;
    }
    .tab-item:hover {
      text-decoration: none;
    }
  </style>
{% endblock %}

{% block content %}
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Expenses Listing </h1>
      <h3 class="subtitle">for {{ today_date }}</h3>  
    </div>
  </div>
  <div class="hero-foot">
    <nav class="tabs is-boxed m-0">
      <div class="container">
        <ul>
          <li class="{{ 'is-active' if cat=='all' }}" >
            <a class="tab-item" href="{{url_for('expenses.show',category='all' )}}">All</a>
          </li>
          {% for category in categories %}
          <li class="{{ 'is-active' if cat==category.name }}" >
            <a class="tab-item" href="{{url_for('expenses.show',category=category.name )}}">{{category.name}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </nav>
  </div>
</section>

<div class="container">
  <table class="table is-hoverable">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Date</th>
        <th scope="col">Category</th>
        <th scope="col">Source</th>
        <th scope="col">Description</th>
        <th scope="col">Amount</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for expense in expenses %}
      <tr>
        <td>{{loop.index}}</td>
        <td>{{expense.created_at.date().strftime("%d %b %Y")}}</td>
        <td>{{expense.cat.name}}</td>
        <td>{{expense.source}}</td>
        <td>{{expense.description}}</td>
        <td>$ {{expense.amount}}</td>
        <td>
          <a class="mx-2" href="{{url_for('expenses.edit',id=expense.id)}}">
            <span class="icon is-small has-text-info">
              <i class="fas fa-edit"></i>
            </span>
          </a>
          <a class="mx-2" href="{{url_for('expenses.delete',id=expense.id)}}">
            <span class="icon is-small has-text-danger">
              <i class="fas fa-trash-alt"></i>
            </span>
          </a>
        </td>
      </tr>
      {% endfor %}
      <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <strong>Total Expenses</strong>
          </td>
          <td>
            <strong>
              $ 
              {% if total == 0 %}
                0.00
              {% else %}
                {{total}}
              {% endif %}
            </strong>
          </td>
          <td></td>
        </tr>
    </tbody>
  </table>
  <div class="my-5">
    <a id="hideButton" class="btn btn-primary" href="{{url_for('expenses.new')}}" >
      <span class="icon is-small">
        <i class="fas fa-plus"></i>
      </span> 
      <span>Expenses</span>
    </a>
    <button class="btn btn-success" onclick="window.print()" >
      <span class="icon is-small">
        <i class="fas fa-print"></i>
      </span> 
      Statement
    </button>
  </div>
</div>

{% endblock %}

app_web/blueprints/expenses/templates/expenses/statement.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Expenses - {{ month }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <style>
      body {
        margin: 0;
        font-size: 80%;
        font-family: 'Montserrat', sans-serif;
      }
      tr { 
        page-break-inside: avoid;
      }
      table {
        border-top: 1px solid #dee2e6;
        border-bottom: 1px solid #dee2e6;
      }
    </style>
  </head>
  <body>
    <div class="container is-fluid p-0">
      <section class="hero is-dark">
        <div class="hero-body">
          <div class="container">
            <h1 class="title">Expenses Statement </h1>
            <h3 class="subtitle">for {{ month }}</h3>  
          </div>
        </div>
      </section>

      <div class="container is-fluid p-0">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">No.</th>
              <th scope="col">Date</th>
              <th scope="col">Category</th>
              <th scope="col">Source</th>
              <th scope="col">Description</th>
              <th scope="col">Amount</th>
            </tr>
          </thead>
          <tbody>
            {% for expense in expenses %}
            <tr>
              <td>{{loop.index}}</td>
              <td>{{expense.created_at.date().strftime("%d %b %Y")}}</td>
              <td>{{expense.cat.name}}</td>
              <td>{{expense.source}}</td>
              <td>{{expense.description}}</td>
              <td>$ {{expense.amount}}</td>
            </tr>
            {% endfor %}
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td><strong>Total Expenses</strong></td>
              <td>
                <strong>
                  $ 
                  {% if total == 0 %}
                    0.00
                  {% else %}
                    {{total}}
                  {% endif %}
                </strong>
              </td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app_web/blueprints/expenses/templates/expenses/summary.html
{% extends "_layout.html" %}
{% block title %}
  Summary
{% endblock %}
{% block content %}
  <section class="hero is-dark">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">Monthly Expenses Summary</h1>
        <h3 class="subtitle">for {{ month_year }}</h3>
      </div>
    </div>
  </section>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Category</th>
          <th scope="col">Total Amount ($)</th>
        </tr>
      </thead>
      <tbody>
        {% for obj in month_exp %}
          <tr>
            <td>{{obj.name}}</td>
            <td>{{ obj.expenses | sum(attribute='amount') }}</td>
          </tr>
        {% endfor %}
        <tr>
          <td><strong>Total {{month_year}} Expenses</strong></td>
          <td><strong>{{ total | sum(attribute='amount') }}</strong></td>
        </tr>
      </tbody>
    </table>
  </div>
{% endblock %}