app_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, jsonify
from models.user import User
from models.expense import Expense
from models.category import Category
from flask_login import login_user, current_user, login_required
import datetime
from peewee import fn
from decimal import *

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
  return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():
  user_password = request.form['password']
  user = User(username=request.form['username'].lower(),email=request.form['email'].lower(),password=user_password)
  if user.save():
    login_user(user)
    Category.create(name="General Expenses", user=user.id)
    flash("Welcome! Start tracking your money by recording your expenses according to Category.","link")
    return redirect(url_for('users.show', username=user.username))
  else:
    for error in user.errors:
      flash(error,"danger")
    return render_template('users/new.html')

@users_blueprint.route('/<username>', methods=["GET"])
@login_required
def show(username):
  user = User.get_or_none(User.username == username)
  if not user:
    flash("User not found.", "danger")
    return redirect(url_for('user.show', username = current_user.username))
  else:
    if current_user.id == user.id:
      return render_template('users/show.html',username=user.username)
    else:
      flash("Unauthorized to visit this user's profile.", "danger")
      return redirect(url_for('user.show', username = current_user.username))
    

@users_blueprint.route('/<id>', methods=['POST'])
@login_required
def update(id):
  user = User.get_or_none(id=id)
  user.password = request.form['password']
  user.email = request.form['email']
  user.username = request.form['username']
  if user.save():
    flash("Profile updated.","link")
    return redirect(url_for('users.show', username=user.username))
  else:
    for error in user.errors:
      flash(error,"danger")
    return redirect(url_for('users.show', username=user.username))

@users_blueprint.route('/dashboard', methods=["GET"])
@login_required
def dashboard():

  def _get_last_twelve(current):
    last_twelve = [] # last 12months
    # check current month and year => 1, 2021
    month = current.month
    year = current.year
    for i in range(12):  # loop for 12 times
      # if month - 1 not equal to zero, then year == current.year, else year == current.year - 1 and month == 12
      if not month == 0:
        last_twelve.append((year, month))
      else:
        month = 12
        year = year - 1
        last_twelve.append((year, month))
      month = month - 1
    last_twelve.reverse()
    return last_twelve

  def _get_category_monthly_total(category,twelve):
    expenses_list = []
    for pairs in twelve:
      ttl = Expense.select(fn.SUM(Expense.amount).alias('total')).where(Expense.cat == category, Expense.month==months[pairs[1]],Expense.created_at.year==pairs[0])
      expenses_list.append(0 if ttl[0].total == None else str(ttl[0].total))
    return expenses_list

  months = { 1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec' }
  categories = Category.select().where(Category.user==current_user.id)
  current = datetime.datetime.now()
  twelve = _get_last_twelve(current)

  data = {}
  '''format of data
  data = { 
    "General" : 100 ,
    "Food" : 150 ,
  }
  '''
  result = {}
  '''format of result
  result = {
    "Total": [],
    "General": [],
  }
  '''
  month_labels = []
  aggregate = [] # to collect aggregate expenses for each month
  category_labels = []
  category_ids = []

  for cat in categories:
    category_labels.append(cat.name)
    category_ids.append(cat.id)
    result[cat.name] = _get_category_monthly_total(cat, twelve)

  for pairs in twelve:
    ttl = Expense.select(fn.SUM(Expense.amount).alias('total')).where(Expense.cat.in_(category_ids), Expense.month==months[pairs[1]],Expense.created_at.year==pairs[0])
    month_labels.append(f"{months[pairs[1]]}, {pairs[0]}")
    aggregate.append(0 if ttl[0].total == None else str(ttl[0].total))
  result["Total"] = aggregate
  print(result['Total'][11])
  return render_template(
    'users/dashboard.html', 
    labels = category_labels, 
    month_year = f'{datetime.date.today().strftime("%b")} {current.year}',
    month_labels = month_labels,
    main_values = result,
  )

app_web/blueprints/users/templates/users/_level.html
<p class="subtitle text-primary has-text-centered">{{ today_date }}</p>
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Income</p>
      <p class="title text-warning">3,200</p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Expenditure</p>
      <p class="title text-warning">{{ main_values['Total'][11] }}</p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Balance</p>
      <p class="title text-warning">456K</p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Likes</p>
      <p class="title text-warning">789</p>
    </div>
  </div>
</nav>

app_web/blueprints/users/templates/users/dashboard.html
{% extends "_layout.html" %}
{% block title %}
  Dashboard
{% endblock %}

{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

<div id="dashboard" class="text-light p-5">
  <div class="columns is-multiline">

    <div class="column is-full">
      <canvas id="mainChart" class="chart-item box"></canvas>
    </div>

    <div class="column is-half">
      <div class="chart-item box text-right">
        <div class="select is-rounded is-small">
          <select id="bar-month-select">
            {% for month in month_labels %}
              <option value="{{loop.index}}" {{'selected' if loop.index == 12 }}>{{month}}</option>
            {% endfor %}
          </select>
        </div>
        <canvas id="catChart"></canvas>
      </div>
    </div>

    <div class="column is-half">
      <div class="chart-item box text-right">
        <div class="select is-rounded is-small">
          <select id="pie-month-select">
            {% for month in month_labels %}
              <option value="{{loop.index}}" {{'selected' if loop.index == 12 }}>{{month}}</option>
            {% endfor %}
          </select>
        </div>
        <canvas id="pieChart"></canvas>
      </div>
    </div>

  </div>
</div>

<script>
  const bgColors = [
    'rgba(255, 99, 132, 0.2)', // 1. red
    'rgba(54, 162, 235, 0.2)', // 2. light blue
    'rgba(255, 206, 86, 0.2)', // 3. yellow
    'rgba(75, 192, 192, 0.2)', // 4. cyan
    'rgba(153, 102, 255, 0.2)', // 5. purple
    'rgba(255, 159, 64, 0.2)', // 6. orange
    'rgba(167, 255, 131, 0.2)', // 7. green
    'rgba(255, 182, 193, 0.2)', // 8. pink
    'rgba(0, 0, 255, 0.2)', // 9. blue
    'rgba(169, 169, 169, 0.2)', // 10. grey
    'rgba(202,187,233, 0.2)', // 11. light purple
  ]
  const borderColors = [
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
    'rgba(167, 255, 131, 1)',
    'rgba(255, 182, 193, 1)',
    'rgba(0, 0, 255, 1)',
    'rgba(169, 169, 169, 1)',
    'rgba(202,187,233, 1)', // 11. light purple
  ]
  Chart.defaults.global.defaultFontColor = 'white';

  const labels = {{ labels | safe }}
  const monthLabels = {{ month_labels | safe }}
  const mainValues = {{ main_values | safe }}
  
  // LINE
  let mainCtx = document.getElementById('mainChart');
  let datum = []
  let index = 0
  for (let key in mainValues) {
    datum.push({
      label: key,
      data: mainValues[key],
      borderColor: borderColors[index],
      borderWidth: 1.5,
    })
    index++
  }
  const createLineChart = () => {
    let lineChart = new Chart(mainCtx, {
      type: 'line',
      data: {
        labels:  monthLabels,
        datasets: datum,
      },
      options: {
        title: {
          display: true,
          text: 'Overall Expenses for Last 12 Months',
          position: 'top',
          fontSize: 16,
        },
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true,
              callback: function(value, index, values) {
                return '$ ' + value + '.00';
              }
            }
          }]
        }
      }
    });
  }
  // BAR
  let barChart;
  let barCtx = document.getElementById('catChart');
  let barSelected = 11 // default should be the latest month (last index number)
  let barValues = []
  $('#bar-month-select').on('change', function() {
    barSelected = this.value - 1
    updateBarChart()
  });
  const updateBarChart = () => {
    barValues = []
    for (let label of labels){
      barValues.push(mainValues[label][barSelected])
    }
    barChart.data.datasets[0].data = barValues
    barChart.options.title.text = `Expenses for ${monthLabels[barSelected]}`
    barChart.update()
  }
  const createBarChart = () => {
    barValues = []
    for (let label of labels){
      barValues.push(mainValues[label][barSelected])
    }
    barChart = new Chart(barCtx, {
      type: 'bar',
      data: {
        labels:  labels,
        datasets: [{
          label: 'Total($)',
          data:  barValues,
          backgroundColor: bgColors,
          borderColor: borderColors,
          borderWidth: 1,
        }]
      },
      options: {
        legend: { display: false },
        title: {
          display: true,
          text: `Expenses for ${monthLabels[barSelected]}`,
          position: 'top',
          fontSize: 16,
        },
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true,
              callback: function(value, index, values) {
                return '$ ' + value + '.00';
              }
            }
          }]
        }
      }
    });
  }
  // PIE
  let pieChart;
  let pieCtx = document.getElementById('pieChart');
  let pieSelected = 11 // default should be the latest month (last index number)
  let pieValues = []
  $('#pie-month-select').on('change', function() {
    pieSelected = this.value - 1
    updatePieChart()
  });
  const updatePieChart = () => {
    pieValues = []
    for (let label of labels){
      pieValues.push(mainValues[label][pieSelected])
    }
    pieChart.data.datasets[0].data = pieValues
    pieChart.options.title.text = `Composition of Expenses for ${monthLabels[pieSelected]}`
    pieChart.update()
  }
  const createPieChart = () => {
    pieValues = []
    for (let label of labels){
      pieValues.push(mainValues[label][pieSelected])
    }
    pieChart = new Chart(pieCtx, {
      type: 'pie',
      data:  {
        labels: labels,
        datasets: [{
          data: pieValues,
          backgroundColor: bgColors,
          borderColor: borderColors,
          borderWidth: 1,
        }],
      },
      options: {
        title: {
          display: true,
          text: `Composition of Expenses for ${monthLabels[pieSelected]}`,
          position: 'top',
          fontSize: 16,
        },
        animation: { animateScale: true },
      }
    });
  }
  // first render with default values
  createLineChart()
  createBarChart()
  createPieChart()
</script>
{% endblock %}

app_web/blueprints/users/templates/users/new.html
{% extends "_layout.html" %}
{% block title %}
  Sign Up
{% endblock %}
{% block content %}
  <div id="sign-up-page">
    <div class="form-item card">
      <h1 class="subtitle">Sign Up</h1>
      <form action="{{url_for('users.create')}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="field">
          <div class="control has-icons-left">
            <input type='text' required name='username' placeholder="Username" class="input" />
            <span class="icon is-small is-left">
              <i class="fas fa-user"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <div class="control has-icons-left">
            <input type='email' required name='email' placeholder="Email" class="input" />
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <div class="control has-icons-left">
            <input type='password' required name='password' placeholder="Password" class="input" />
            <span class="icon is-small is-left">
              <i class="fas fa-lock"></i>
            </span>
          </div>
        </div>
        <button type="submit" class="button is-success is-fullwidth">Sign Up</button>
        <p class="help">By tapping Sign Up, you agree to our Terms of Service and Privacy Policy.</p>
      </form>
    </div>
  </div>

{% endblock %}

app_web/blueprints/users/templates/users/show.html
{% extends "_layout.html" %}
{% block title %}
  Setting
{% endblock %}
{% block header %}
  <style>
    #setting-card {
      min-height: calc(100vh - var(--NAVHEIGHT) - var(--FOOTERHEIGHT) );
    }
  </style>
{% endblock %}
{% block content %}
<div class="columns container is-fullhd my-3">
  <aside class="menu column is-12-mobile is-4-desktop ">
    <!-- profile -->
    <div class="media mb-3">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://ui-avatars.com/api/?name={{current_user.username}}&background=0e153a&color=fff" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">{{ current_user.username }}</p>
        <p class="subtitle is-6">{{ current_user.email }}</p>
      </div>
    </div>
    <!-- menu to toggle -->
    <ul class="menu-list nav nav-tabs" role="tablist">
      <li><a class="" href="#account" role="tab" data-toggle="tab">My Account</a></li>
      <li><a class="active" href="#category" role="tab" data-toggle="tab">My Categories</a></li>
    </ul>
  </aside>

  <!-- toggled content -->
  <div id="setting-card" class="column pr-5 is-12-mobile is-8-desktop ">
    <div class="tab-content card h-100">
      <div role="tabpanel" class="tab-pane" id="account" >
        <section class="hero is-dark">
          <div class="hero-body">
            <div class="container">
              <h1 class="subtitle m-0"><strong>Profile</strong></h1>
              <p>Manage and protect your account</p>
            </div>
          </div>
        </section>

        <form class="container p-5" action="{{url_for('users.update', id=current_user.id )}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <div class="field">
            <label class="label">Username</label>
            <div class="control has-icons-left">
              <input type='text' required value={{current_user.username}} name='username' placeholder="Username" class="input" />
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
            </div>
          </div>
          <div class="field">
            <label class="label">Email</label>
            <div class="control has-icons-left">
              <input type='email' required value={{current_user.email}} name='email' placeholder="Email" class="input" />
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
            </div>
          </div>
          <div class="field">
            <label class="label">Password</label>
            <div class="control has-icons-left">
              <input type='password' required name='password' placeholder="Password" class="input" />
              <span class="icon is-small is-left">
                <i class="fas fa-lock"></i>
              </span>
            </div>
          </div>
          <button type="submit" class="button is-success is-fullwidth">Save</button>
        </form>
      </div>
      <div role="tabpanel" class="tab-pane active" id="category" >
        <section class="hero is-dark">
          <div class="hero-body">
            <div class="container">
              <h1 class="subtitle m-0 d-flex justify-content-between">
                <strong>My Expenses Categories</strong>
                <button id="toggle-button" class="button is-link is-small">
                  <span class="icon is-small">
                    <i class="fas fa-plus"></i>
                  </span> 
                  <span>Add New Category</span>
                </button>
              </h1>
              <small>Max 10 categories</small>
            </div>
          </div>
        </section>
        <!-- card list-item to list all categories -->
        {% for cat in current_user.categories %}
        <div class="px-5 panel-block d-flex justify-content-between">
          <span>
            {{loop.index}}.  {{cat.name}}
          </span>
          <div class="is-right">
            <button onclick="editCategory( '{{ cat.id | safe}}','{{ cat.name | safe }}' )" class="button is-small is-info">
              <span class="icon">
                <i class="fas fa-edit"></i>
              </span>
            </button>
            <button onclick="deleteCategory( '{{ cat.id | safe}}','{{ cat.name | safe }}' )" class="button is-small is-danger">
              <span class="icon">
                <i class="fas fa-trash-alt"></i>
              </span>
            </button>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!-- confirm delete modal -->
<div id="delete-modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <section class="modal-card-body text-center py-5" style="height: 250px;">
      <p class="subtitle py-5">
        Confirm delete "<strong id="selected"></strong>" category?
      </p>
      <div class="my-5 d-flex justify-content-center">
        <form id="delete-form" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <input class="button mx-2 is-small is-primary" type="submit" value="Confirm" />
        </form>
        <button id="close-delete" class="button mx-2 is-small is-danger">Cancel</button>
      </div>
    </section>
  </div>
</div>
<!-- modal form to add new category -->
<div id="category-modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Add New Category</p>
      <button id="close-button" class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <form class="container p-5" action="{{url_for('categories.create')}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="field">
          <label class="label">Category Name</label>
          <div class="control has-icons-left">
            <input type='text' required name='name' placeholder="Name" class="input" />
            <span class="icon is-small is-left">
              <i class="fas fa-poll-h"></i>
            </span>
          </div>
        </div>
        <button type="submit" class="button is-link is-fullwidth">Save</button>
      </form>
    </section>
    <footer class="m-0 modal-card-foot"></footer>
  </div>
</div>
<!-- modal form to edit category -->
<div id="edit-modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Edit Category</p>
      <button id="close-edit" class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <form id="edit-form" class="container p-5" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="field">
          <label class="label">Category Name</label>
          <div class="control has-icons-left">
            <input id="edit-input" type='text' required name='name' placeholder="Name" class="input" />
            <span class="icon is-small is-left">
              <i class="fas fa-poll-h"></i>
            </span>
          </div>
        </div>
        <button type="submit" class="button is-warning is-fullwidth">Save</button>
      </form>
    </section>
    <footer class="m-0 modal-card-foot"></footer>
  </div>
</div>

<script>
  const toggleModal = () => {
    if ($("#category-modal").hasClass('is-active')) {
      $("#category-modal").removeClass('is-active')
    } else {
      $("#category-modal").addClass('is-active')
    }
  }
  $("#toggle-button").click(function(){
    toggleModal()
  })
  $("#close-button").click(function(){
    toggleModal()
  })
  
  const apiUrl = "{{ 'FLASK_ENV' | getenv }}" == 'production' ? 'https://personal-mgt-app.herokuapp.com' :'http://localhost:5000'
  const deleteCategory = (catId, name) => {
    $("#selected").html(name)
    $("#delete-form").attr('action', `${apiUrl}/categories/${catId}/delete`)
    $("#delete-modal").addClass('is-active')
  }
  const editCategory = (catId, name) => {
    $("#edit-input").val(name)
    $("#edit-form").attr('action', `${apiUrl}/categories/${catId}`)
    $("#edit-modal").addClass('is-active')
  }
  $("#close-delete").click(function(){
    $("#delete-modal").removeClass('is-active')
  })
  $("#close-edit").click(function(){
    $("#edit-modal").removeClass('is-active')
  })
</script>
{% endblock %}